<project xmlns="http://maven.apache.org/POM/4.0.0">
  
  	<modelVersion>4.0.0</modelVersion>
  	<groupId>net.alexf1789</groupId>
  	<artifactId>SwingHash</artifactId>
  	<version>1.0</version>
  	<name>SwingHash</name>
  	<description>Simple program which computes hash of files and text</description>
  
	<dependencies>
		<!-- Source: https://mvnrepository.com/artifact/com.formdev/flatlaf -->
		<dependency>
		    <groupId>com.formdev</groupId>
		    <artifactId>flatlaf</artifactId>
		    <version>3.7.1</version>
		    <scope>compile</scope>
		</dependency>
		
		<!-- Source: https://mvnrepository.com/artifact/com.google.code.gson/gson -->
		<dependency>
		    <groupId>com.google.code.gson</groupId>
		    <artifactId>gson</artifactId>
		    <version>2.14.0</version>
		    <scope>compile</scope>
		</dependency>
	</dependencies>
  
</project>